services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./sentimental_analysis:/app/sentimental_analysis
    environment:
      - PYTHONUNBUFFERED=1