name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.10.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.16
    - name: Install dependencies
      run: |
        pip install pytest-cov
        echo requirements installed
    - name: Run the tests
      env:
        SCRAPEOPS_API_SECRET: ${{ secrets.SCRAPEOPS_API_SECRET }}
      run: |
          pip install -r requirements.txt
          (cd sentimental_analysis && pytest --ds=sentimental_analysis.settings --cov=./ --cov-config=test/.coveragerc --cov-report=xml)

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./sentiment_analysis/coverage.xml
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
